services:
  jupyter-lab:
    image: wine_color_classification:milestone4
    ports:
      - "8889:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 16G
    platform: linux/amd64

  terminal:
    image: wine_color_classification:milestone4
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 16G
    platform: linux/amd64